### ISSUE TITLE
getReport() Resource path doesn't exist

### ISSUE THREAD

**Issue by cmi90** [lai3221/amz_adv_api_php#3]
Please fix report path, instead `$req = $this->operation($type . "reports/{$reportId}");` must be `$req = $this->operation("reporting/reports/{$reportId}");`

line `956` in `SponsoredProductsRequests` trait

thank you

**Comment by lai3221** [comment]
V2 is `$req = $this->operation($type . "reports/{$reportId}");`
V3 is `$req = $this->operation("reporting/reports/{$reportId}")`
thank you

**Comment by lai3221** [comment]
close
